### PR TITLE
Add input cards for muon simulations

### PR DESCRIPTION
**Pull request by rlopezcoto**
Following the discussion with @YusukeSuda, who produced the latest muon simulations, this is the addition of the corsika/simtel files for muon production that were used for that. 
I created a separate branch to contain them, but it may as well be that the best way to store them is to give them a sensible name and add them to the corsika/simtel branches, let's hear opinions.

### CODE REVIEW

**Comment by rlopezcoto** [comment]
@jsitarek @mexanick @Voutsi do you agree with this proposal for storing the input cards for muon simulations or would you prefer to include them in the `simtel`/`corsika` branches?

**Comment by maxnoe** [comment]
Why do we need to duplicate the LST config? Wouldn't it be enough to add the muon input card to the `corsika` branch and use the common configuration from the `simtel` branch?

**Comment by rlopezcoto** [comment]
> Why do we need to duplicate the LST config? Wouldn't it be enough to add the muon input card to the `corsika` branch and use the common configuration from the `simtel` branch?

yeah, that was the question, I do not think that in the `simtel` input anything apart from the `telescope_transmission` is changed for the several muon files to be produced.

**Comment by maxnoe** [comment]
@rlopezcoto Ok, then we should just make the telescope transmission configurable in the config

**Comment by jsitarek** [comment]
Hi @rlopezcoto 
We went with  Pratik (@mpratik73) over the input card and we have some comments:
1) you generate the muons with one single slope over the whole energy range, while in reality the index changes with energy (in MAGIC there are a few ranges simulated), do you apply later on weighting in the analysis?
2) max impact you set to just ~10m, This is because you want full rings, however due to the muon scattering you can have events which have the original impact of 10m or so and still end up hitting the middle of the dish. I think it is much better to have a bit higher value here, 20-30 m, and you can always select the events that are closer. Simulation time for muons is either way negligible. 
3) you use the atmosphere number  36, while the ongoing LST1+MAGIC simulations use a different atmosphere:
IACT ATMOFILE atmprof_ecmwf_north_winter_fixed.dat
ATMOSPHERE 99 Y     // Use a custom profile by filename (this must come _AFTER_ IACT ATMOFILE ...!)
see https://github.com/cta-observatory/lst-sim-config/blob/corsika/config_LST1_2MAGIC_point_gammas.cfg

**Comment by rlopezcoto** [comment]
@maxnoe ,@jsitarek: apologies, I completely missed these replies.

@maxnoe: shall I then commit these two input cards to the corsika and simtel branches and skip this PR? How do you want to make the telescope transmission configurable?

@jsitarek :
1. No weighting is applied, actually I discussed it with @mpratik the other day and he said he was gonna check if it made any difference in the telescope transmission derived for MAGIC data. If this is the case, we should also investigate if it also affects LST.
2. It is true that simulation time is negligible, but then analysis of the muons is not that much. The muons that you mean I would be expecting to have the same light yield that the ones we have now (assuming we apply the same cuts for complete muons), right?
3. Yes, this is probably coming from some original input card from Konrad... I will change that

**Comment by mexanick** [comment]
> @rlopezcoto Ok, then we should just make the telescope transmission configurable in the config

The telescope transmission can be manipulated through the `sim_runner` configuration file, however in this case it will apply to **all** telescopes of the array as the command-line inputs of `sim_telarray` can not distinguish between the telescopes. I.e. if such production would only be analyzed from the LST side, then there's no need in a new configuration tag, but if MAGIC would like to use the same muon production, a new configuration tag must be created with a oneliner change.

**Comment by moralejo** [comment]
@mexanick Muon productions have to be telescope-specific, so we should not include the MAGIC telescopes. They will need their own, but I don't know how urgent this is. @jsitarek may comment.

**Comment by mexanick** [comment]
> @mexanick Muon productions have to be telescope-specific, so we should not include the MAGIC telescopes. They will need their own, but I don't know how urgent this is. @jsitarek may comment.

in this case we can proceed without changes on sim_telarray side. Suggested changes in the sim_runner config would be to limit the number of telescopes to 1 (so we don't simulate MAGICs with only noise) and scan over the telescope_transmission parameter within a predefined range.

**Comment by jsitarek** [comment]
> @mexanick Muon productions have to be telescope-specific, so we should not include the MAGIC telescopes. They will need their own, but I don't know how urgent this is. @jsitarek may comment.

I think we do not need to worry about the MAGIC muons for the moment. Once you sort it out for LST, we can follow the procedure with similar input cards for MAGIC. It is fast to generate them (but as Ruben said the analysis time might be an issue)

**Comment by rlopezcoto** [comment]
I will close this one and move the discussion to #22

**Pull request closed without merging**
