### PR TITLE
commenting out TSTART (needed for curved option) and making nscat a s…

### PR DESCRIPTION
**Pull request by Voutsi**
…teerable par.
This pull request modifies the configuration files in order to be compatible with Corsika when is compiled with CURVED option enabled. CURVED is not supporting the TSTART handle. It is always set in true value (as we want). Removing the keyword doesn't affect simulations performed with Corsika when CURVED is not enabled, since in IACT option, TSTART is set to true by default. So it is redundant.

Once the request is approved we can move on with zd > 70deg nodes.

### CODE REVIEW

**Review by jsitarek — APPROVED** [review]
fine with me.

**Comment by jsitarek** [comment]
just one comment - you use FIXHEI option in the input cards, this option is also not compatible with the curved option for em-primary particles. Didn't you have some problems with it for gammas ?
the values 0 0 are either way defaults.

**Comment by Voutsi** [comment]
Thanks for the feedback. No, I didn't encounter any problems in the test runs I tried with CURVED option.

**Comment by moralejo** [comment]
> Thanks for the feedback. No, I didn't encounter any problems in the test runs I tried with CURVED option.

So it does not complain just because you set the default values?

**Review by moralejo — APPROVED** [review]

**Comment by Voutsi** [comment]
> So it does not complain just because you set the default values?

It seems so. If I add some non-zero value (zero is the default), e.g. 50E5, meaning fixing the 1st interaction at 50km I am getting the following error msg:
UNALLOWED CHOICE OF FIXHEI IN CURVED VERSION 
 THE FIRST INTERACTION CANNOT BE FIXED FOR PRIMARY PARTICLE TYPE 
 SEE KEYWORD: FIXHEI

For FIXHEI = 0. the jobs are running ok. I will comment it out in any case since we always use the default value.

**Pull request merged**
