### PR TITLE
removing CTA/LST PROD tags from the file names

### PR DESCRIPTION
**Pull request by jsitarek**
I removed the production tags from the MAGIC file names. 
@moralejo if this is the naming that you had in mind just merge the PR. 

Please note however that MAGIC[12].cfg still include:
CTA-PROD4-site.cfg
CTA-PROD4-common.cfg
so when those files will be renamed (together with the LST ones), MAGIC[12].cfg has to be updated again.

here is the full list of the MAGIC-specific files needed for the simulations:
* camera_CTA-MAGIC_MajorityTrigger-3NN.dat
* LightCollection-MAGIC2-smooth_simtel.dat
* MAGIC1.cfg
* MAGIC2.cfg
* mirror_CTA-MAGIC1_new_corrected-mirror-positions.dat
* mirror_CTA-MAGIC2_new_corrected-mirror-positions.dat
* pmt_MAGIC1_test.cfg
* pmt_MAGIC2_test.cfg
* prompt_ap-M1.dat
* prompt_ap-M2.dat
* pulse_MAGIC_FWHM1.75ns.dat
* pulse_MAGIC_FWHM2.00ns.dat
* qe-hamamatsu_M1_koji.dat
* qe-hamamatsu_M2_koji.dat
* ref_M1_average_20220201.dat
* ref_M2_average.dat

(i.e. all the MAGIC files currently in sim_telarray branch are indeed needed)

### CODE REVIEW

**Comment by moralejo** [comment]
Thanks for this clean-up, looks good to me!

**Comment by maxnoe** [comment]
Could we maybe improve the consistency a bit?

E.g. replacing `M1{1,2}` with `MAGIC{1,2}` and maybe it's also nicer to have all files start with `MAGIC{1,2}` and then have the description of what it is?

I.e. `MAGIC1_qe_hamamatsu.dat`, `MAGIC1_pmt.dat`?

**Comment by jsitarek** [comment]
Hi @maxnoe 
I agree about M[12]==> MAGIC[12], done now

but about putting MAGIC in front, this is not following the scheme of the config files in sim_telarray. most of the files have style like the current files, with the subsystem first and then what is the actual config, e.g. pmt_specs_R11920.cfg
Only exception are the production tags that are first (e.g. CTA-ULTRA6-pmt.cfg), but those tags we decided not to include. 
I think it is better to keep the original scheme, otherwise we will end up with a complete mess if the old files and new are put together

**Comment by jsitarek** [comment]
Hi, I'm going to merge it as it is now. 
Since we will need at least one more update with the names of common and site configs, we can rediscuss the naming of the other files then

**Pull request merged**
